LOGIN_URL = '/login'
SIGN_UP_URL = '/signUp'
LOGOUT_URL = '/logout'
SETTING_URL = '/setting'
UPDATE_PROFILE_URL = '/update_profile'
WRITE_NOTICE_URL = '/write_notice'
NOTICE_DETAIL_URL = '/notice_detail'
